# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish

on:
  workflow_dispatch:

  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: git  version # refs/tags/v0.0.5
      run: echo ${{ github.ref }}
    - name: pom version # 0.0.1
      run: mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q
    - name: export pom version
      run: export PROJECT_VERSION=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
    - name: echo
      run: echo $PROJECT_VERSION

    - name: validate version
      run: echo 'okk'

    - name: Publish
      run: echo 'done'
      #run: mvn -q deploy
      env:
        MAVEN_USERNAME: ${{ secrets.USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE_KEY }}
